apiVersion: v1
kind: Service
metadata:
  name: nodeapp-test-service
spec:
  selector:
    app: nodeapp-test
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110